app/scripts/zodiac/point-node-inspector.jsx
app/scripts/zodiac/skill-graph.jsx
src/views/tests/zodiac-editor.test.jsx
src/views/zodiac/zodiac-editor.jsx

- Added new unit test to cover start node changing

Change start node status of nodes within zodiac editor

---

src/cpt/point-node.class.php
src/cpt/skill.class.php

Save start node changes to the API

---

src/controllers/admin.controller.php
src/controllers/controller.aclass.php
src/controllers/data.controller.php
src/controllers/login.controller.php
src/controllers/main.controller.php
src/controllers/script.controller.php

- Created an abstract generic Controller class
- Refactored all existing controllers to extend the generic controller

Generic controller

---

app/scripts/character/character-builder.jsx
app/scripts/character/character-skills-panel.jsx
src/cpt/character.class.php

- Character XP and PP values are now displayed
- Users cannot pick more nodes than their XP
fix #35

Character XP restrictions

---

src/cpt/skill.class.php
src/routes/graph-data.route.php
src/views/zodiac/zodiac-editor.jsx

- Save proper link data when new nodes are present
- Added additional checks on foreaches to prevent PHP warnings
fix #58

Restored zodiac save mechanism

---

index.php

Added meta property for mobile viewports

---

src/cpt/skill.class.php
src/routes/graph-data.route.php

Switched foreach checks from array_key_exists to the more reliable is_array
fix #58

Restore zodiac save mechanism

---

app/scripts/zodiac/skill-graph.jsx

Made zodiac draggable again

---

src/views/tests/zodiac-editor.test.jsx
src/views/zodiac/zodiac-editor.jsx

- Reinforced unit tests related to node deletion to reflect this
fix #65

Deletion of outgoing links when deleting node has links

---

app/scripts/character/character-skills-panel.jsx
src/controllers/script.controller.php

- Switched Bootstrap JS lib from 4.0.0-alpha to 3.3.5

Better CharacterSkillsPanel layout

---

app/scripts/character/character-builder.jsx
app/scripts/character/character-skills-panel.jsx
app/scripts/sidenav/sidenav.jsx
app/scripts/zodiac/skill-graph.jsx
app/styles/character/character-builder.scss
src/views/zodiac/zodiac-editor.jsx

- SkillGraph is now grid-agnostic and should be wrapped based on context
- Moved around UI elements in character builder to always display save button and inspector

Revised SkillGraph layout

---

acf-json/group_5701f1d054d1d.json
app/scripts/character/character-builder.jsx
app/scripts/character/character-skills-panel.jsx
app/scripts/zodiac/perk-button-group.jsx
app/scripts/zodiac/skill-node-inspector.jsx
app/tests/character/character-builder.test.jsx
src/cpt/character.class.php
src/cpt/skill.class.php
src/routes/graph-data.route.php

Users can now buy upgrades on their skills using their perk points.
Saving will not be permitted if their perk point current total is below 0.

Character perk points

---

app/tests/character/character-builder.test.jsx
app/tests/zodiac/skill-graph.test.jsx
package.json
src/views/tests/zodiac-editor.test.jsx

Updated NPM packages

---

app/scripts/character/character-builder.jsx

Correctly handle empty character builds

---

src/routes/graph-data.route.php

Added permissions to graph-data route to limit updating to admins

---

dockerfile
hosting/php.ini

Added php.ini directives for input variables

---

app/scripts/character/character-builder.jsx

- Accounted for start skill + auto skill in XP calculation
fix #85

Prevented start nodes from being picked/unpicked

---

app/scripts/character/character-builder.jsx
app/scripts/zodiac/skill-graph.jsx
app/styles/zodiac/skill-graph.scss

- Added zoom support for mousewheel on SkillGraph
- Added overlaying button on SkillGraph to reset zoom back to 1
fix #128

Graph zoom mechanism

---

acf-json/group_5702efceb0f12.json
src/controllers/login.controller.php
src/controllers/main.controller.php
src/cpt/character.class.php

- Added custom capability to Character to allow user accounts to publish them
- Refined ACF model around user active character
- Redirect to homepage instead of admin after login
fix #47

Hides the active character field from the user register form

---

app/scripts/character/character-builder.jsx
app/scripts/character/character-skills-panel.jsx
package.json

Modify energy point total based on node count

---

app/styles/login/login.scss
package.json
src/controllers/login.controller.php
src/views/login/register-form.php

- Hid ACF fields from registration/login forms
- Added notice about weird redirection bug
fix #47 
fix #138

Added password field to registration

---

app/scripts/character/character-sheet-skill.jsx
app/scripts/character/character-sheet.jsx

- Fetch up to 100 skills instead of 10 when generating character sheets
- Check for invalid perks leftover by ACF when rendering character sheets
- Removed unused function (derp)

Sheet fixes

---

app/scripts/character/character-sheet-skill.jsx
app/scripts/sidenav/sidenav-user-panel.jsx
app/scripts/zodiac/skill-node-inspector.jsx
app/styles/sidenav/sidenav-user-panel.scss

- Match all occurences of power levels
- Prevent clickthrough on character menu toggle button

General fixes

---

acf-json/group_5866b9bc21de4.json
acf-json/group_5866c6194c774.json
acf-json/group_5866c7b923573.json
acf-json/group_5866c905b6a02.json
acf-json/group_586ad431ae860.json
app/app.jsx
app/scripts/campaign/campaign-archive.page.jsx
app/scripts/campaign/campaign-article.page.jsx
app/scripts/templates/article.page.jsx
app/styles/campaign/campaign-archive.scss
app/styles/campaign/campaign-article.scss
app/styles/templates/archive.scss
package.json
src/controllers/data.controller.php
src/controllers/script.controller.php
src/cpt/campaign.class.php
src/cpt/event.class.php
src/cpt/skill.class.php
src/routes/campaign-events.route.php

Ajout de la fondation du module Campagne du site.
* Modèles de données `Campaign` et `Event` 
* Archive des campagnes
* Page Campagne individuelle

Module Campagne
